uge6/my-pizza/Models/BasketItem.cs
namespace my_pizza.Models
{
    public class BasketItem
    {
        public Product Product { get; set; }
        public int Qty { get; set; }
    }
}

uge6/my-pizza/Models/CatalogContext.cs
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace my_pizza.Models
{
    public class CatalogContext : DbContext
    {
        public CatalogContext(DbContextOptions<CatalogContext> options)
            : base(options)
        { }

        public DbSet<Category> Categories { get; set; }
        public DbSet<Product> Products { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Data Source=my_pizza.db");
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.Entity<Category>().HasData(new Category
            {
                Id = 1,
                Name = "Pizza"
            },
            new Category
            {
                Id = 2,
                Name = "Durum"
            });

            builder.Entity<Product>().HasData(new Product
            {
                Id = 1,
                Name = "Vesuvio",
                Description = "Tomat, ost og skinke",
                Price = 69,
                CategoryId = 1
            },
            new Product
            {
                Id = 2,
                Name = "Vegetariana",
                Description = "Tomat, ost, paprika, champignon, ananas, asparges og løg",
                Price = 74,
                CategoryId = 1
            },
            new Product
            {
                Id = 3,
                Name = "Hawaii",
                Description = "Tomat, ost, skinke og ananas",
                Price = 71,
                CategoryId = 1
            },
            new Product
            {
                Id = 4,
                Name = "Pepperoni",
                Description = "Tomat, ost og pepperoni",
                Price = 69,
                CategoryId = 1
            },
            new Product
            {
                Id = 5,
                Name = "Capricciosa",
                Description = "Tomat, ost, skinke og champignon",
                Price = 73,
                CategoryId = 1
            },
            new Product
            {
                Id = 6,
                Name = "Kylling Durum",
                Description = "Serveres med salat og dressing",
                Price = 59,
                CategoryId = 2
            },
            new Product
            {
                Id = 7,
                Name = "Kebab Durum",
                Description = "Serveres med salat og dressing",
                Price = 59,
                CategoryId = 2
            },
            new Product
            {
                Id = 8,
                Name = "Græsk Bøf Durum",
                Description = "Serveres med salat og dressing",
                Price = 59,
                CategoryId = 2
            },
            new Product
            {
                Id = 9,
                Name = "Falafel Durum",
                Description = "Serveres med salat og dressing",
                Price = 59,
                CategoryId = 2
            },
            new Product
            {
                Id = 10,
                Name = "Skinke Durum",
                Description = "Serveres med salat og dressing",
                Price = 59,
                CategoryId = 2
            });
        }
    }
}

uge6/my-pizza/Models/Category.cs
using System.Collections.Generic;

namespace my_pizza.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public ICollection<Product> Products { get; set; }
    }
}

uge6/my-pizza/Models/ErrorViewModel.cs
using System;

namespace my_pizza.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

uge6/my-pizza/Models/Product.cs
namespace my_pizza.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }

        public int CategoryId { get; set; }
        public Category Category { get; set; }
    }
}

uge6/my-pizza/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using my_pizza.Models;

namespace my_pizza.Controllers
{
    public class CatalogController : Controller
    {
        private readonly CatalogContext _context;
        public CatalogController(CatalogContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int id = 1)
        {
            var category = await Task.FromResult(_context.Categories.FirstOrDefault(x => x.Id == id));
            return View(category);
        }
    }
}

uge6/my-pizza/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using my_pizza.Models;

namespace my_pizza.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

uge6/my-pizza/Infrastructure/ViewComponts/ProductListViewComponent.cs
namespace my_pizza.ViewComponts
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using my_pizza.Models;

    public class ProductListViewComponent : ViewComponent
    {
        private readonly CatalogContext _context;
        public ProductListViewComponent(CatalogContext context) 
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(int categoryId)
        {
            var items = await GetProductsAsync(categoryId);
            return View(items);
        }

        private Task<List<Product>> GetProductsAsync(int categoryId)
        {
            return _context.Products.Where(x => x.CategoryId == categoryId).ToListAsync();
        }
    }
}

uge6/my-pizza/Infrastructure/ViewComponts/ProductViewComponent.cs
namespace my_pizza.ViewComponts
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using my_pizza.Models;

    public class ProductViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(Product product)
        {
            return await Task.FromResult(View(product));
        }
    }
}

uge6/my-pizza/Views/Catalog/Components/Product/Default.cshtml
@model Product
@Model.Name&nbsp;&nbsp;<button class="add-to-basket" data-id="@Model.Id" data-qty="1">Add</button><br />

uge6/my-pizza/Views/Catalog/Index.cshtml
@model my_pizza.Models.Category

<h1>@Model.Name</h1>

@await Component.InvokeAsync("ProductList", @Model.Id)

uge6/my-pizza/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

uge6/my-pizza/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - my_pizza</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">my_pizza</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - my_pizza - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>